### ISSUE TITLE
simulate_bundle RPC returns success on an empty list of transactions

### ISSUE THREAD

**Issue by segfaultdoc** [jito-foundation/jito-solana#165]
This is misleading, return an error.

**Comment by anoushk1234** [comment]
hey @segfaultdoc the simulate bundle in the rpc uses the simulate bundle in bank.rs, also the test cases for this function are only written in bank.rs so my question is should change the function in bank or in rpc?

**Comment by anoushk1234** [comment]
> > hey @segfaultdoc the simulate bundle in the rpc uses the simulate bundle in bank.rs, also the test cases for this function are only written in bank.rs so my question is should change the function in bank or in rpc?
> 
> I think we should check for the empty list in the RPC method and return an `invalid_params` error to the caller

gotcha, implementing this now, thanks

**Comment by anoushk1234** [comment]
hey @segfaultdoc have made a pr for this #221
