### ISSUE TITLE
error: failed to get `anchor-lang` as a dependency of package `solana-sdk v1.15.0`

### ISSUE THREAD

**Issue by eliotstock** [jito-foundation/jito-solana#188]
help, can't build!

```
git clone https://github.com/jito-foundation/jito-solana.git
Cloning into 'jito-solana'...
remote: Enumerating objects: 217494, done.
remote: Counting objects: 100% (7644/7644), done.
remote: Compressing objects: 100% (1393/1393), done.
remote: Total 217494 (delta 6414), reused 7319 (delta 6209), pack-reused 209850
Receiving objects: 100% (217494/217494), 294.48 MiB | 7.05 MiB/s, done.
Resolving deltas: 100% (158941/158941), done.
$cd jito-solana/
$cargo build
    Updating git repository `https://github.com/solana-labs/crossbeam`
    Updating crates.io index
error: failed to get `anchor-lang` as a dependency of package `solana-sdk v1.15.0 (/home/e/r/ts/jito-solana/sdk)`

Caused by:
  failed to load source for dependency `anchor-lang`

Caused by:
  Unable to update /home/e/r/ts/jito-solana/anchor/lang

Caused by:
  failed to read `/home/e/r/ts/jito-solana/anchor/lang/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by eliotstock** [comment]
This is on Ubuntu 22.10, if it matters. And I did this beforehand:

`sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler`

**Comment by buffalu** [comment]
please fetch jito-solana again and run `git submodule update --init --recursive`.

We will update the readme shortly with these instructions

**Comment by eliotstock** [comment]
Thanks, with the submodules down I got past this build error (and onto the next one).

**Comment by depool-live** [comment]
please fix it in release too

error: failed to get `anchor-lang` as a dependency of package `solana-sdk v1.13.6 (~jito-solana-1.13.6-jito/sdk)`
Caused by:
  failed to load source for dependency `anchor-lang`
Caused by:
  Unable to update ~jito-solana-1.13.6-jito/anchor/lang
Caused by:
  failed to read `~jito-solana-1.13.6-jito/anchor/lang/Cargo.toml`
Caused by:
  No such file or directory (os error 2)

**Comment by meyerbro** [comment]
> 

You need to just read the previous msgs...
