### ISSUE TITLE
RPC crashes on simulate_transaction

### ISSUE THREAD

**Issue by segfaultdoc** [jito-foundation/jito-solana#313]
Running v1.14.17-jito, the RPC periodically crashes with:
```
ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solRpcEl" one=1i message="panicked at 'simulation bank must be frozen', runtime/src/bank.rs:4077:9" location="runtime/src/bank.rs:4077:9" version="\"1.14.17 (src:devbuild; feat:3488713414)
```

todo:
- run 1.14.16-jito and v1.14.17 vanilla client to determine if issue is upstream

**Comment by Arrowana** [comment]
I wonder if that's simply calling too early and there is a missing protection in the solana validator. I can repro this by sending a transaction early on a solana-test-validator with a finalized commitment.
