### ISSUE TITLE
Bank::collect_balances collects balances for transactions that fail to lock

### ISSUE THREAD

**Issue by buffalu** [jito-foundation/jito-solana#50]
#### Problem
In Bank::collect_balances, we collect balances on accounts that failed to lock

#### Proposed Solution
We should only collect balances for transactions that have a corresponding Ok(()) on lock_results

**Comment by allanperlee** [comment]
Hi @buffalu, I probably could work on this, are you reviewing and accepting pull requests?

**Comment by anoushk1234** [comment]
> 

Hey @buffalu I've implemented this in #219 let me know if this is good, thanks
