### ISSUE TITLE
1.17.16 does not build

### ISSUE THREAD

**Issue by TurtleSnail** [jito-foundation/jito-solana#566]
```
root@m13:~# git clone https://github.com/jito-foundation/jito-solana.git --recurse-submodules
Cloning into 'jito-solana'...
remote: Enumerating objects: 369101, done.
remote: Counting objects: 100% (48990/48990), done.
remote: Compressing objects: 100% (12758/12758), done.
remote: Total 369101 (delta 36532), reused 47489 (delta 35522), pack-reused 320111
Receiving objects: 100% (369101/369101), 343.69 MiB | 13.36 MiB/s, done.

...

root@m13:~/jito-solana# git checkout tags/$TAG
Note: switching to 'tags/v1.17.16-jito'.

...

root@m13:~/jito-solana# git submodule update --init --recursive
root@m13:~/jito-solana# CI_COMMIT=$(git rev-parse HEAD) scripts/cargo-install-all.sh --validator-only ~/.local/share/solana/install/releases/"$TAG"
OSTYPE IS: linux-gnu
Install location: /root/.local/share/solana/install/releases/v1.17.16-jito (release)
+ cd target/perf-libs
+ [[ -r /root/.cache/solana-perf-v0.19.3.tgz ]]
+ cp /root/.cache/solana-perf-v0.19.3.tgz solana-perf.tgz
+ tar zxvf solana-perf.tgz
./cuda-10.0/
./cuda-10.0/libcl-crypt.so
./cuda-10.0/cuda-version.txt
./cuda-10.0/libcuda-crypt.so
./cuda-10.1/
./cuda-10.1/libcl-crypt.so
./cuda-10.1/cuda-version.txt
./cuda-10.1/libcuda-crypt.so
./cuda-10.2/
./cuda-10.2/libcl-crypt.so
./cuda-10.2/cuda-version.txt
./cuda-10.2/libcuda-crypt.so
./libpoh-simd.so
./libsigning.so
./signing_public.h
./signing.signed.so
./signing.so
./signing_test
./solana-perf-HEAD.txt
+ [[ ! -r /root/.cache/solana-perf-v0.19.3.tgz ]]
+ echo v0.19.3-1
+ /root/jito-solana/cargo build --profile release --bin solana --bin solana-bench-tps --bin solana-faucet --bin solana-gossip --bin solana-install --bin solana-keygen --bin solana-ledger-tool --bin solana-log-analyzer --bin solana-net-shaper --bin solana-validator --bin rbpf-cli --bin solana-genesis
+ exec cargo +1.73.0 build --profile release --bin solana --bin solana-bench-tps --bin solana-faucet --bin solana-gossip --bin solana-install --bin solana-keygen --bin solana-ledger-tool --bin solana-log-analyzer --bin solana-net-shaper --bin solana-validator --bin rbpf-cli --bin solana-genesis
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.2
   Compiling libc v0.2.149
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.109
   Compiling serde v1.0.189
   Compiling typenum v1.15.0

...

   Compiling jsonrpc-derive v18.0.0
   Compiling ed25519-dalek-bip32 v0.2.0
   Compiling rolling-file v0.2.0
   Compiling ctrlc v3.4.1
error: failed to run custom build command for `etcd-client v0.11.1`

Caused by:
  process didn't exit successfully: `/root/jito-solana/target/release/build/etcd-client-46450057aa650c5c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto
  cargo:rerun-if-changed=proto/auth.proto
  cargo:rerun-if-changed=proto/kv.proto
  cargo:rerun-if-changed=proto/rpc.proto
  cargo:rerun-if-changed=proto/v3election.proto
  cargo:rerun-if-changed=proto/v3lock.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10:
  Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by brycole** [comment]
> ```
> root@m13:~# git clone https://github.com/jito-foundation/jito-solana.git --recurse-submodules
> Cloning into 'jito-solana'...
> remote: Enumerating objects: 369101, done.
> remote: Counting objects: 100% (48990/48990), done.
> remote: Compressing objects: 100% (12758/12758), done.
> remote: Total 369101 (delta 36532), reused 47489 (delta 35522), pack-reused 320111
> Receiving objects: 100% (369101/369101), 343.69 MiB | 13.36 MiB/s, done.
> 
> ...
> 
> root@m13:~/jito-solana# git checkout tags/$TAG
> Note: switching to 'tags/v1.17.16-jito'.
> 
> ...
> 
> root@m13:~/jito-solana# git submodule update --init --recursive
> root@m13:~/jito-solana# CI_COMMIT=$(git rev-parse HEAD) scripts/cargo-install-all.sh --validator-only ~/.local/share/solana/install/releases/"$TAG"
> OSTYPE IS: linux-gnu
> Install location: /root/.local/share/solana/install/releases/v1.17.16-jito (release)
> + cd target/perf-libs
> + [[ -r /root/.cache/solana-perf-v0.19.3.tgz ]]
> + cp /root/.cache/solana-perf-v0.19.3.tgz solana-perf.tgz
> + tar zxvf solana-perf.tgz
> ./cuda-10.0/
> ./cuda-10.0/libcl-crypt.so
> ./cuda-10.0/cuda-version.txt
> ./cuda-10.0/libcuda-crypt.so
> ./cuda-10.1/
> ./cuda-10.1/libcl-crypt.so
> ./cuda-10.1/cuda-version.txt
> ./cuda-10.1/libcuda-crypt.so
> ./cuda-10.2/
> ./cuda-10.2/libcl-crypt.so
> ./cuda-10.2/cuda-version.txt
> ./cuda-10.2/libcuda-crypt.so
> ./libpoh-simd.so
> ./libsigning.so
> ./signing_public.h
> ./signing.signed.so
> ./signing.so
> ./signing_test
> ./solana-perf-HEAD.txt
> + [[ ! -r /root/.cache/solana-perf-v0.19.3.tgz ]]
> + echo v0.19.3-1
> + /root/jito-solana/cargo build --profile release --bin solana --bin solana-bench-tps --bin solana-faucet --bin solana-gossip --bin solana-install --bin solana-keygen --bin solana-ledger-tool --bin solana-log-analyzer --bin solana-net-shaper --bin solana-validator --bin rbpf-cli --bin solana-genesis
> + exec cargo +1.73.0 build --profile release --bin solana --bin solana-bench-tps --bin solana-faucet --bin solana-gossip --bin solana-install --bin solana-keygen --bin solana-ledger-tool --bin solana-log-analyzer --bin solana-net-shaper --bin solana-validator --bin rbpf-cli --bin solana-genesis
>    Compiling proc-macro2 v1.0.69
>    Compiling unicode-ident v1.0.2
>    Compiling libc v0.2.149
>    Compiling version_check v0.9.4
>    Compiling autocfg v1.1.0
>    Compiling cfg-if v1.0.0
>    Compiling syn v1.0.109
>    Compiling serde v1.0.189
>    Compiling typenum v1.15.0
> 
> ...
> 
>    Compiling jsonrpc-derive v18.0.0
>    Compiling ed25519-dalek-bip32 v0.2.0
>    Compiling rolling-file v0.2.0
>    Compiling ctrlc v3.4.1
> error: failed to run custom build command for `etcd-client v0.11.1`
> 
> Caused by:
>   process didn't exit successfully: `/root/jito-solana/target/release/build/etcd-client-46450057aa650c5c/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=proto
>   cargo:rerun-if-changed=proto/auth.proto
>   cargo:rerun-if-changed=proto/kv.proto
>   cargo:rerun-if-changed=proto/rpc.proto
>   cargo:rerun-if-changed=proto/v3election.proto
>   cargo:rerun-if-changed=proto/v3lock.proto
>   cargo:rerun-if-changed=proto
> 
>   --- stderr
>   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10:
>   Could not find `protoc` installation and this build crate cannot proceed without
>       this knowledge. If `protoc` is installed and this crate had trouble finding
>       it, you can set the `PROTOC` environment variable with the specific path to your
>       installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases
> 
>   For more information: https://docs.rs/prost-build/#sourcing-protoc
> 
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> ```

This is a pretty googleable error.  Try this thread.  https://github.com/hyperium/tonic/issues/1047

**Comment by TurtleSnail** [comment]
apt install -y protobuf-compiler libprotobuf-dev

fixed it

**Comment by brycole** [comment]
> apt install -y protobuf-compiler libprotobuf-dev
> 
> fixed it

its part of the install instructions, check it out if you haven't. you might run into more dependency issues.

here -> https://jito-foundation.gitbook.io/mev/jito-solana/building-the-software#computer-setup

"sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler"
