### ISSUE TITLE
MEV Stage fails silently when address malformed

### ISSUE THREAD

**Issue by segfaultdoc** [jito-foundation/jito-solana#71]
Let's fail fast and panic if the url is malformed so validators aren't stuck scratching their heads.

**Comment by anoushk1234** [comment]
Hey @segfaultdoc just to clarify do you mean this line in the claim_mev_tips function when the validators try to claim their rewards https://github.com/jito-foundation/jito-solana/blob/fbdae674488946094b5e82a73e593b08c7aa2ba1/tip-distributor/src/claim_mev_workflow.rs#L49-L50

**Comment by segfaultdoc** [comment]
This issue's actually been resolved. This was in reference to the URL strings passed down to, what's now called, `block_engine_stage` and `relayer_stage`. Looks like we fail fast and loud now: https://github.com/jito-foundation/jito-solana/blob/master/validator/src/main.rs#L2696

**Comment by anoushk1234** [comment]
gotcha, thanks
