### ISSUE TITLE
Bad code path hit if validator receives any bundles mentioning tip PDAs while the program isn't deployed.

### ISSUE THREAD

**Issue by segfaultdoc** [jito-foundation/jito-solana#73]
The validator should check that the program exists in the DB and only then try to create the init tx.

**Comment by anoushk1234** [comment]
hey @segfaultdoc I think this is implemented here https://github.com/jito-foundation/jito-solana/blob/fbdae674488946094b5e82a73e593b08c7aa2ba1/core/src/bundle_stage.rs#L821
